services:
  web:
    build: .
    env_file: .env
    entrypoint: ["sh", "/app/entrypoint.sh"]
    environment:
      ALLOWED_HOSTS: "209.50.228.34,localhost,127.0.0.1"
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_NAME: "${POSTGRES_DB:-synexdb}"
      DB_USER: "${POSTGRES_USER:-synexuser}"
      DB_PASSWORD: "${POSTGRES_PASSWORD:-synexpass}"
      GUNICORN_TIMEOUT: "${GUNICORN_TIMEOUT:-120}"
      GUNICORN_GRACEFUL_TIMEOUT: "${GUNICORN_GRACEFUL_TIMEOUT:-30}"
      GUNICORN_WORKERS: "${GUNICORN_WORKERS:-2}"
      GUNICORN_KEEPALIVE: "${GUNICORN_KEEPALIVE:-5}"
      GUNICORN_LOG_LEVEL: "${GUNICORN_LOG_LEVEL:-info}"
    command: []
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./media:/app/media
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-synexdb}"
      POSTGRES_USER: "${POSTGRES_USER:-synexuser}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-synexpass}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backup:
    image: postgres:16-alpine
    env_file: .env
    entrypoint: >
      sh -c "while true; do
        echo '[backup] iniciando dump...';
        PGPASSWORD=$${POSTGRES_PASSWORD} pg_dump -h $${POSTGRES_HOST:-db} -U $${POSTGRES_USER} $${POSTGRES_DB} > /backups/backup_$$(date +%Y%m%d%H%M).sql &&
        find /backups -type f -mtime +7 -delete;
        sleep 86400;
      done"
    volumes:
      - pgbackups:/backups
    depends_on:
      - db
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.13
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL:-admin@synex.com}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-changeme123}"
    ports:
      - "5051:80"
    depends_on:
      - db

volumes:
  pgdata:
  pgbackups:
