# Generated by Django 6.0 on 2025-12-09 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacao',
            name='prioridade',
            field=models.CharField(choices=[('A', 'Alta (Importante)'), ('M', 'Média'), ('B', 'Baixa (Normal)')], default='B', max_length=1),
        ),
    ]
