# Generated by Django 6.0 on 2025-12-09 01:15

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_anotacao_prioridade'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacao',
            name='fonte',
            field=models.URLField(blank=True, help_text='Link da documentação ou artigo', null=True),
        ),
        migrations.AddField(
            model_name='anotacao',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
