# Generated by Django 6.0 on 2025-12-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_metaobjetivo_tarefa_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacao',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
