# Generated by Django 6.0 on 2025-12-09 14:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_anotacao_favorito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterField(
            model_name='anotacao',
            name='fonte',
            field=models.URLField(blank=True, help_text='Link da documentacao ou artigo', null=True),
        ),
        migrations.AlterField(
            model_name='anotacao',
            name='prioridade',
            field=models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baixa')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('B', 'Baixa'), ('M', 'Media'), ('A', 'Alta')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('todo', 'A Fazer'), ('doing', 'Em Andamento'), ('done', 'Concluido')], default='todo', max_length=10),
        ),
        migrations.CreateModel(
            name='SessaoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao_min', models.PositiveIntegerField()),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes', to='core.materia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data', '-created_at'],
            },
        ),
    ]
