# Generated by Django 6.0 on 2025-12-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
