# Generated by Django 6.0 on 2025-12-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_perfil_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='premium_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
