# Generated by Django 6.0 on 2025-12-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_perfil_premium_activated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('todo', 'A Fazer'), ('doing', 'Em Andamento'), ('review', 'Revisao'), ('done', 'Concluido')], default='todo', max_length=10),
        ),
    ]
