# Generated by Django 6.0 on 2025-12-10 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_tarefa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaoestudo',
            name='tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes_estudo', to='core.tarefa'),
        ),
    ]
