# Generated by Django 6.0 on 2026-01-08 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sessaoestudo_tarefa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('abacate', 'Abacate Pay')], default='abacate', max_length=32)),
                ('provider_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='created', max_length=32)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='BRL', max_length=8)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('abacate', 'Abacate Pay')], default='abacate', max_length=32)),
                ('provider_id', models.CharField(blank=True, max_length=120)),
                ('kind', models.CharField(choices=[('one_time', 'One time'), ('subscription', 'Subscription')], max_length=32)),
                ('status', models.CharField(default='created', max_length=32)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='BRL', max_length=8)),
                ('checkout_url', models.URLField(blank=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.subscription')),
            ],
        ),
    ]
