"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.
"""

import os
from pathlib import Path
import dj_database_url



BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega variáveis de ambiente (.env) se python-dotenv estiver disponível
try:
    from dotenv import load_dotenv  # type: ignore
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    env_path = BASE_DIR / '.env'
    if env_path.exists():
        for raw_line in env_path.read_text(encoding='utf-8').splitlines():
            line = raw_line.strip()
            if not line or line.startswith('#') or '=' not in line:
                continue
            key, value = line.split('=', 1)
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if key and key not in os.environ:
                os.environ[key] = value

# Segurança
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-change-me'
    else:
        raise RuntimeError("SECRET_KEY must be set in production.")

# --- CORREÇÃO AQUI ---
# Pega do .env ou inicia lista vazia
ALLOWED_HOSTS = [h for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h]

# Se estiver em modo DEBUG, garantimos que localhost E o túnel funcionem
if DEBUG:
    # Adicionamos os hosts locais e o wildcard do Cloudflare
    ALLOWED_HOSTS.extend(['synexstudy.top', 'www.synexstudy.top','localhost', '127.0.0.1', '[::1]', '.trycloudflare.com'])

# Se NÃO for debug e a lista estiver vazia, erro (produção)
if not DEBUG and not ALLOWED_HOSTS:
    raise RuntimeError("ALLOWED_HOSTS must be set in production.")

# --- FIM DA CORREÇÃO ---

# CSRF (Isso aqui já estava quase certo, mantive ajustado)
CSRF_TRUSTED_ORIGINS = [
    'https://*.trycloudflare.com',
    'https://127.0.0.1',
    'http://127.0.0.1',
    'https://synexstudy.top',
    'https://www.synexstudy.top',
]
# Aplicativos
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'taggit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'core.middleware.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.favoritos_globais',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

USE_POSTGRES = os.getenv('USE_POSTGRES', 'True').lower() == 'true'
# Configuração Padrão (Local / Docker)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'synexdb'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'options': '-c client_encoding=UTF8',
        },
    }
}


# Configuração de Produção (Sobrescreve a de cima se existir DATABASE_URL)
# Isso pega o banco de dados do Render automaticamente
database_url = os.environ.get('DATABASE_URL')
if database_url:
    DATABASES['default'] = dj_database_url.parse(database_url)


    

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# Static & Media
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Auth redirects
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'kanban'
LOGOUT_REDIRECT_URL = 'home'

# Security flags (use True/secure values em produção)
# AVISO (deploy): em produção, force SECURE_SSL_REDIRECT/SESSION_COOKIE_SECURE/CSRF_COOKIE_SECURE.
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'False').lower() == 'true'
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'False').lower() == 'true'
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# E-mail (produção usa SMTP; dev pode trocar backend)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')


# Promo / plano demo
# AVISO (deploy): desative promo code em produção para evitar bypass de receita.
PROMO_PREMIUM_CODE = os.getenv('PROMO_PREMIUM_CODE', 'PREMIUM-DEMO')
try:
    PROMO_PREMIUM_DAYS = int(os.getenv('PROMO_PREMIUM_DAYS', '7'))
except ValueError:
    PROMO_PREMIUM_DAYS = 7


# App info
APP_VERSION = os.getenv('APP_VERSION', '0.075 beta')

# Abacate Pay
SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000')
ABACATEPAY_API_URL = os.getenv('ABACATEPAY_API_URL', 'https://api.abacatepay.com/v1')
ABACATEPAY_TOKEN = os.getenv('ABACATEPAY_TOKEN', '')
ABACATEPAY_WEBHOOK_SECRET = os.getenv('ABACATEPAY_WEBHOOK_SECRET', '')
ABACATEPAY_CHECKOUT_PATH = os.getenv('ABACATEPAY_CHECKOUT_PATH', 'checkout')
ABACATEPAY_CANCEL_PATH = os.getenv('ABACATEPAY_CANCEL_PATH', 'subscriptions/{subscription_id}/cancel')
ABACATEPAY_CURRENCY = os.getenv('ABACATEPAY_CURRENCY', 'BRL')
ABACATEPAY_PREMIUM_PRICE_CENTS = int(os.getenv('ABACATEPAY_PREMIUM_PRICE_CENTS', '2990'))
ABACATEPAY_ONE_TIME_PRICE_CENTS = int(os.getenv('ABACATEPAY_ONE_TIME_PRICE_CENTS', '2990'))
ABACATEPAY_ONE_TIME_DAYS = int(os.getenv('ABACATEPAY_ONE_TIME_DAYS', '30'))
ABACATEPAY_PIX_QRCODE_PATH = os.getenv('ABACATEPAY_PIX_QRCODE_PATH', 'pixQrCode/create')
ABACATEPAY_PIX_SIMULATE_PATH = os.getenv('ABACATEPAY_PIX_SIMULATE_PATH', 'pixQrCode/simulate-payment')
ABACATEPAY_SIMULATE_PIX = os.getenv('ABACATEPAY_SIMULATE_PIX', 'false')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
